# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3bb548ac0bc66f848466cb4064b74e65447268958d39608254b79a108662ab2ab39dce95ecac124804c788b87daf6333f7eaefa1c53462bc17158966edafff7

test:
  secret_key_base: a01fe02bc1d4523fb2174a97fda516a897055c1547118cd72600b3366ee07fa152de4e3ff43c668a8e1875ecbfd63ba4e8a7adcc7ec8aeb8e228be45e8e26541

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
